version: "3.8"

#Update the connection among these microservices before starting the container.
# 
networks:
  architecture:
    driver: bridge

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - architecture
    depends_on:
      - frontend
      - api
      
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    links:
      - api
    networks:
      - architecture
  
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
    # host:container
      - 5003:5003
    volumes:
      - ./api:/app
    links:
      - db 
    networks:
      - architecture

  db:
    image: postgres:15.3-alpine3.18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - architecture
