version: "3.8"

#Update the connection among these microservices before starting the container.
# 

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    depends_on:
      - api
  
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
    # host:container
      - 5003:5003
    volumes:
      - ./api:/app

  db:
    image: postgres:15.3-alpine3.18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
